# Generated by Django 5.2.8 on 2025-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usermission',
            name='unique_mission_user_date',
        ),
        migrations.AddConstraint(
            model_name='usermission',
            constraint=models.UniqueConstraint(fields=('user', 'mission', 'date'), name='unique_mission_user_date'),
        ),
    ]
